# Generated by Django 3.0.2 on 2020-01-03 12:43

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspaces', '0001_initial'),
        ('django_q', '0009_auto_20171009_0915'),
        ('fyle', '0001_initial'),
        ('quickbooks_online', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkspaceSchedule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Created at datetime')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Updated at datetime')),
                ('schedule', models.OneToOneField(help_text='Stores Fyle refresh token', on_delete=django.db.models.deletion.PROTECT, to='django_q.Schedule')),
                ('workspace', models.OneToOneField(help_text='Reference to Workspace model', on_delete=django.db.models.deletion.PROTECT, to='workspaces.Workspace')),
            ],
        ),
        migrations.CreateModel(
            name='TaskLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(help_text='Task Status', max_length=255)),
                ('detail', django.contrib.postgres.fields.jsonb.JSONField(help_text='Task response')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Created at datetime')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Updated at datetime')),
                ('bill', models.OneToOneField(help_text='Reference to Bill', on_delete=django.db.models.deletion.PROTECT, to='quickbooks_online.Bill')),
                ('expense_group', models.OneToOneField(help_text='Reference to Expense group', on_delete=django.db.models.deletion.PROTECT, to='fyle.ExpenseGroup')),
                ('task', models.OneToOneField(help_text='Django Q task reference', on_delete=django.db.models.deletion.PROTECT, to='django_q.Task')),
                ('workspace', models.OneToOneField(help_text='Reference to Workspace model', on_delete=django.db.models.deletion.PROTECT, to='workspaces.Workspace')),
            ],
        ),
    ]
