# Generated by Django 3.0.3 on 2020-12-21 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_auto_20200420_0434"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="tasklog",
            table="task_logs",
        ),
    ]
