# Generated by Django 3.0.2 on 2020-01-13 14:27

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quickbooks_online', '0001_initial'),
        ('tasks', '0002_remove_tasklog_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasklog',
            name='bill',
            field=models.OneToOneField(help_text='Reference to Bill', null=True, on_delete=django.db.models.deletion.PROTECT, to='quickbooks_online.Bill'),
        ),
        migrations.AlterField(
            model_name='tasklog',
            name='detail',
            field=django.contrib.postgres.fields.jsonb.JSONField(help_text='Task response', null=True),
        ),
    ]
