# Generated by Django 3.0.2 on 2020-01-13 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0001_initial'),
        ('tasks', '0003_auto_20200113_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasklog',
            name='workspace',
            field=models.ForeignKey(help_text='Reference to Workspace model', on_delete=django.db.models.deletion.PROTECT, to='workspaces.Workspace'),
        ),
    ]
