# Generated by Django 3.0.3 on 2021-03-22 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fyle', '0014_auto_20210120_1831'),
        ('tasks', '0004_tasklog_bill_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasklog',
            name='expense_group',
            field=models.ForeignKey(help_text='Reference to Expense group', null=True, on_delete=django.db.models.deletion.PROTECT, to='fyle.ExpenseGroup', unique=True),
        ),
    ]
