# Generated by Django 3.0.3 on 2021-05-04 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quickbooks_online', '0010_qboexpense_qboexpenselineitem'),
        ('tasks', '0004_tasklog_bill_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklog',
            name='qbo_expense',
            field=models.ForeignKey(help_text='Reference to QBO Expense', null=True, on_delete=django.db.models.deletion.PROTECT, to='quickbooks_online.QBOExpense'),
        ),
    ]
