# Generated by Django 3.0.3 on 2021-06-28 06:12

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [('tasks', '0005_tasklog_qbo_expense')]

    operations = [
        migrations.AddField(
            model_name='tasklog',
            name='quickbooks_errors',
            field=django.contrib.postgres.fields.jsonb.JSONField(
                help_text='Quickbooks Errors', null=True
            ),
        )
    ]
