# Generated by Django 3.0.2 on 2020-01-14 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fyle', '0002_expense_approved_at'),
        ('quickbooks_online', '0001_initial'),
        ('django_q', '0009_auto_20171009_0915'),
        ('tasks', '0005_auto_20200113_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklog',
            name='task',
            field=models.OneToOneField(help_text='Django Q task reference', null=True, on_delete=django.db.models.deletion.PROTECT, to='django_q.Task'),
        ),
        migrations.AlterField(
            model_name='tasklog',
            name='bill',
            field=models.ForeignKey(help_text='Reference to Bill', null=True, on_delete=django.db.models.deletion.PROTECT, to='quickbooks_online.Bill'),
        ),
        migrations.AlterField(
            model_name='tasklog',
            name='expense_group',
            field=models.ForeignKey(help_text='Reference to Expense group', on_delete=django.db.models.deletion.PROTECT, to='fyle.ExpenseGroup'),
        ),
    ]
