# Generated by Django 3.0.3 on 2021-08-16 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quickbooks_online', '0012_creditcardcredit_creditcardcreditlineitem'),
        ('tasks', '0006_tasklog_quickbooks_errors'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklog',
            name='credit_card_credit',
            field=models.ForeignKey(help_text='Reference to CreditCardCredit', null=True, on_delete=django.db.models.deletion.PROTECT, to='quickbooks_online.CreditCardCredit'),
        ),
    ]
