# Generated by Django 3.0.2 on 2020-01-14 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_auto_20200114_0528'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasklog',
            name='task',
        ),
        migrations.AddField(
            model_name='tasklog',
            name='task_id',
            field=models.CharField(help_text='Django Q task reference', max_length=255, null=True),
        ),
    ]
