# Generated by Django 3.0.2 on 2020-01-15 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fyle', '0004_auto_20200115_1103'),
        ('tasks', '0007_auto_20200114_0627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasklog',
            name='expense_group',
            field=models.ForeignKey(help_text='Reference to Expense group', null=True, on_delete=django.db.models.deletion.PROTECT, to='fyle.ExpenseGroup'),
        ),
    ]
