# Generated by Django 3.0.2 on 2020-01-17 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_auto_20200115_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklog',
            name='type',
            field=models.CharField(default='', help_text='Task type (FETCH_EXPENSES / CREATE_BILL)', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workspaceschedule',
            name='task',
            field=models.ManyToManyField(help_text='Tasks under the Schedule', to='tasks.TaskLog'),
        ),
    ]
