# Generated by Django 3.0.3 on 2020-03-08 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_auto_20200117_0729'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WorkspaceSchedule',
        ),
    ]
