# Generated by Django 3.2.14 on 2024-05-07 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_auto_20220714_0911'),
    ]

    operations = [
        migrations.AddField(
            model_name='error',
            name='repetition_count',
            field=models.IntegerField(default=0, help_text='repetition count for the error'),
        ),
    ]
