# Generated by Django 3.2.14 on 2024-11-27 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_error_repetition_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='error',
            name='article_link',
            field=models.TextField(blank=True, help_text='Article link', null=True),
        ),
        migrations.AddField(
            model_name='error',
            name='attribute_type',
            field=models.CharField(blank=True, help_text='Error Attribute type', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='error',
            name='is_parsed',
            field=models.BooleanField(default=False, help_text='Is parsed'),
        ),
    ]
