# Generated by Django 3.2.14 on 2025-01-03 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fyle', '0040_expense_masked_corporate_card_number'),
        ('tasks', '0012_auto_20241127_0730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasklog',
            name='expense_group',
            field=models.ForeignKey(help_text='Reference to Expense group', null=True, on_delete=django.db.models.deletion.PROTECT, to='fyle.expensegroup', unique=True),
        ),
    ]
