# Generated by Django 4.2.20 on 2025-04-14 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0015_alter_tasklog_triggered_by'),
        ('tasks', '0015_error_mapping_error_expense_group_ids'),
    ]

    operations = [
    ]
