# Generated by Django 4.2.22 on 2025-08-11 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0016_merge_20250414_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklog',
            name='re_attempt_export',
            field=models.BooleanField(default=False, help_text='Is re-attempt export'),
        ),
    ]
