# Generated by Django 3.0.3 on 2020-03-10 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("fyle", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bill",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "accounts_payable_id",
                    models.CharField(
                        help_text="QBO Accounts Payable account id", max_length=255
                    ),
                ),
                (
                    "vendor_id",
                    models.CharField(help_text="QBO vendor id", max_length=255),
                ),
                (
                    "department_id",
                    models.CharField(
                        help_text="QBO department id", max_length=255, null=True
                    ),
                ),
                (
                    "transaction_date",
                    models.DateField(help_text="Bill transaction date"),
                ),
                ("currency", models.CharField(help_text="Bill Currency", max_length=5)),
                ("private_note", models.TextField(help_text="Bill Description")),
                ("bill_number", models.CharField(max_length=15, unique=True)),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="Updated at"),
                ),
                (
                    "expense_group",
                    models.OneToOneField(
                        help_text="Expense group reference",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="fyle.ExpenseGroup",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BillLineitem",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "account_id",
                    models.CharField(help_text="QBO account id", max_length=255),
                ),
                (
                    "class_id",
                    models.CharField(
                        help_text="QBO class id", max_length=255, null=True
                    ),
                ),
                (
                    "customer_id",
                    models.CharField(
                        help_text="QBO customer id", max_length=255, null=True
                    ),
                ),
                ("amount", models.FloatField(help_text="Bill amount")),
                (
                    "description",
                    models.CharField(
                        help_text="QBO bill lineitem description",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="Updated at"),
                ),
                (
                    "bill",
                    models.ForeignKey(
                        help_text="Reference to bill",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="quickbooks_online.Bill",
                    ),
                ),
                (
                    "expense",
                    models.OneToOneField(
                        help_text="Reference to Expense",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="fyle.Expense",
                    ),
                ),
            ],
        ),
    ]
