# Generated by Django 3.0.3 on 2020-04-20 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("fyle", "0002_auto_20200420_0434"),
        ("quickbooks_online", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cheque",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "bank_account_id",
                    models.CharField(help_text="QBO Bank account id", max_length=255),
                ),
                (
                    "entity_id",
                    models.CharField(help_text="QBO entity id", max_length=255),
                ),
                (
                    "department_id",
                    models.CharField(
                        help_text="QBO department id", max_length=255, null=True
                    ),
                ),
                (
                    "transaction_date",
                    models.DateField(help_text="Cheque transaction date"),
                ),
                (
                    "currency",
                    models.CharField(help_text="Cheque Currency", max_length=5),
                ),
                ("private_note", models.TextField(help_text="Cheque Description")),
                ("cheque_number", models.CharField(max_length=55, unique=True)),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="Updated at"),
                ),
                (
                    "expense_group",
                    models.OneToOneField(
                        help_text="Expense group reference",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="fyle.ExpenseGroup",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CreditCardPurchase",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "ccc_account_id",
                    models.CharField(help_text="QBO CCC account id", max_length=255),
                ),
                (
                    "entity_id",
                    models.CharField(help_text="QBO entity id", max_length=255),
                ),
                (
                    "department_id",
                    models.CharField(
                        help_text="QBO department id", max_length=255, null=True
                    ),
                ),
                (
                    "transaction_date",
                    models.DateField(help_text="CreditCardPurchase transaction date"),
                ),
                (
                    "currency",
                    models.CharField(
                        help_text="CreditCardPurchase Currency", max_length=5
                    ),
                ),
                (
                    "private_note",
                    models.TextField(help_text="CreditCardPurchase Description"),
                ),
                (
                    "credit_card_purchase_number",
                    models.CharField(max_length=55, unique=True),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="Updated at"),
                ),
                (
                    "expense_group",
                    models.OneToOneField(
                        help_text="Expense group reference",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="fyle.ExpenseGroup",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="JournalEntry",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "transaction_date",
                    models.DateField(help_text="JournalEntry transaction date"),
                ),
                (
                    "currency",
                    models.CharField(help_text="JournalEntry Currency", max_length=5),
                ),
                (
                    "private_note",
                    models.TextField(help_text="JournalEntry Description"),
                ),
                ("journal_entry_number", models.CharField(max_length=55, unique=True)),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="Updated at"),
                ),
                (
                    "expense_group",
                    models.OneToOneField(
                        help_text="Expense group reference",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="fyle.ExpenseGroup",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="JournalEntryLineitem",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "debit_account_id",
                    models.CharField(help_text="QBO Debit account id", max_length=255),
                ),
                (
                    "account_id",
                    models.CharField(help_text="QBO account id", max_length=255),
                ),
                (
                    "class_id",
                    models.CharField(
                        help_text="QBO class id", max_length=255, null=True
                    ),
                ),
                (
                    "entity_id",
                    models.CharField(help_text="QBO entity id", max_length=255),
                ),
                (
                    "entity_type",
                    models.CharField(
                        help_text="QBO Entity Type ( Vendor / Employee )",
                        max_length=255,
                    ),
                ),
                (
                    "customer_id",
                    models.CharField(
                        help_text="QBO customer id", max_length=255, null=True
                    ),
                ),
                (
                    "department_id",
                    models.CharField(
                        help_text="QBO department id", max_length=255, null=True
                    ),
                ),
                (
                    "posting_type",
                    models.CharField(
                        help_text="QBO posting type", max_length=255, null=True
                    ),
                ),
                ("amount", models.FloatField(help_text="JournalEntry amount")),
                (
                    "description",
                    models.CharField(
                        help_text="QBO JournalEntry lineitem description",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="Updated at"),
                ),
                (
                    "expense",
                    models.OneToOneField(
                        help_text="Reference to Expense",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="fyle.Expense",
                    ),
                ),
                (
                    "journal_entry",
                    models.ForeignKey(
                        help_text="Reference to JournalEntry",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="quickbooks_online.JournalEntry",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CreditCardPurchaseLineitem",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "account_id",
                    models.CharField(help_text="QBO account id", max_length=255),
                ),
                (
                    "class_id",
                    models.CharField(
                        help_text="QBO class id", max_length=255, null=True
                    ),
                ),
                (
                    "customer_id",
                    models.CharField(
                        help_text="QBO customer id", max_length=255, null=True
                    ),
                ),
                ("amount", models.FloatField(help_text="credit card purchase amount")),
                (
                    "description",
                    models.CharField(
                        help_text="QBO credit card purchase lineitem description",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="Updated at"),
                ),
                (
                    "credit_card_purchase",
                    models.ForeignKey(
                        help_text="Reference to credit card purchase",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="quickbooks_online.CreditCardPurchase",
                    ),
                ),
                (
                    "expense",
                    models.OneToOneField(
                        help_text="Reference to Expense",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="fyle.Expense",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ChequeLineitem",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "account_id",
                    models.CharField(help_text="QBO account id", max_length=255),
                ),
                (
                    "class_id",
                    models.CharField(
                        help_text="QBO class id", max_length=255, null=True
                    ),
                ),
                (
                    "customer_id",
                    models.CharField(
                        help_text="QBO customer id", max_length=255, null=True
                    ),
                ),
                ("amount", models.FloatField(help_text="Cheque amount")),
                (
                    "description",
                    models.CharField(
                        help_text="QBO cheque lineitem description",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="Updated at"),
                ),
                (
                    "cheque",
                    models.ForeignKey(
                        help_text="Reference to cheque",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="quickbooks_online.Cheque",
                    ),
                ),
                (
                    "expense",
                    models.OneToOneField(
                        help_text="Reference to Expense",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="fyle.Expense",
                    ),
                ),
            ],
        ),
    ]
