# Generated by Django 3.0.2 on 2020-01-14 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickbooks_online', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='department_id',
            field=models.CharField(help_text='QBO department id', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='billlineitem',
            name='class_id',
            field=models.CharField(help_text='QBO class id', max_length=255, null=True),
        ),
    ]
