# Generated by Django 3.0.2 on 2020-01-17 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickbooks_online', '0002_auto_20200114_0703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billlineitem',
            name='description',
            field=models.CharField(help_text='QBO bill lineitem description', max_length=255, null=True),
        ),
    ]
