# Generated by Django 3.0.3 on 2020-07-07 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quickbooks_online", "0003_auto_20200421_1033"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bill",
            name="bill_number",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="cheque",
            name="cheque_number",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="creditcardpurchase",
            name="credit_card_purchase_number",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="journalentry",
            name="journal_entry_number",
            field=models.CharField(max_length=255),
        ),
    ]
