# Generated by Django 3.0.3 on 2020-03-02 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickbooks_online', '0004_billlineitem_customer_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='bank_account_id',
        ),
        migrations.AddField(
            model_name='bill',
            name='accounts_payable_id',
            field=models.CharField(default=None, help_text='QBO Accounts Payable account id', max_length=255),
            preserve_default=False,
        ),
    ]
