# Generated by Django 3.0.3 on 2021-02-03 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [('quickbooks_online', '0008_auto_20210120_1831')]

    operations = [
        migrations.RemoveField(model_name='billpaymentlineitem', name='expense')
    ]
