# Generated by Django 3.0.3 on 2021-01-20 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fyle', '0014_auto_20210120_1831'),
        ('quickbooks_online', '0008_auto_20210120_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='billpayment',
            name='expense_group',
            field=models.OneToOneField(default=1, help_text='Expense group reference', on_delete=django.db.models.deletion.PROTECT, to='fyle.ExpenseGroup'),
            preserve_default=False,
        ),
    ]
