# Generated by Django 3.0.3 on 2021-08-16 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fyle', '0016_expensegroup_response_logs'),
        ('quickbooks_online', '0011_auto_20210722_1446'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCardCredit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ccc_account_id', models.CharField(help_text='QBO CCC account id', max_length=255)),
                ('entity_id', models.CharField(help_text='QBO entity id', max_length=255)),
                ('department_id', models.CharField(help_text='QBO department id', max_length=255, null=True)),
                ('transaction_date', models.DateField(help_text='CreditCardCredit transaction date')),
                ('currency', models.CharField(help_text='CreditCardCredit Currency', max_length=255)),
                ('private_note', models.TextField(help_text='CreditCardCredit Description')),
                ('credit_card_credit_number', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Updated at')),
                ('expense_group', models.OneToOneField(help_text='Expense group reference', on_delete=django.db.models.deletion.PROTECT, to='fyle.ExpenseGroup')),
            ],
            options={
                'db_table': 'credit_card_credits',
            },
        ),
        migrations.CreateModel(
            name='CreditCardCreditLineitem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('account_id', models.CharField(help_text='QBO account id', max_length=255)),
                ('class_id', models.CharField(help_text='QBO class id', max_length=255, null=True)),
                ('customer_id', models.CharField(help_text='QBO customer id', max_length=255, null=True)),
                ('amount', models.FloatField(help_text='credit card credit amount')),
                ('billable', models.BooleanField(help_text='Expense Billable or not', null=True)),
                ('description', models.TextField(help_text='QBO credit card credit lineitem description', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Updated at')),
                ('credit_card_credit', models.ForeignKey(help_text='Reference to credit card credit', on_delete=django.db.models.deletion.PROTECT, to='quickbooks_online.CreditCardCredit')),
                ('expense', models.OneToOneField(help_text='Reference to Expense', on_delete=django.db.models.deletion.PROTECT, to='fyle.Expense')),
            ],
            options={
                'db_table': 'credit_card_credit_lineitems',
            },
        ),
    ]
