# Generated by Django 3.1.14 on 2023-04-11 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickbooks_online', '0012_auto_20210830_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='billlineitem',
            name='detail_type',
            field=models.CharField(default='AccountBasedExpenseLineDetail', help_text='Detail type for the lineitem', max_length=255),
        ),
        migrations.AddField(
            model_name='billlineitem',
            name='item_id',
            field=models.CharField(help_text='QBO item id', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='chequelineitem',
            name='detail_type',
            field=models.CharField(default='AccountBasedExpenseLineDetail', help_text='Detail type for the lineitem', max_length=255),
        ),
        migrations.AddField(
            model_name='chequelineitem',
            name='item_id',
            field=models.CharField(help_text='QBO item id', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='creditcardpurchaselineitem',
            name='detail_type',
            field=models.CharField(default='AccountBasedExpenseLineDetail', help_text='Detail type for the lineitem', max_length=255),
        ),
        migrations.AddField(
            model_name='creditcardpurchaselineitem',
            name='item_id',
            field=models.CharField(help_text='QBO item id', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='qboexpenselineitem',
            name='detail_type',
            field=models.CharField(default='AccountBasedExpenseLineDetail', help_text='Detail type for the lineitem', max_length=255),
        ),
        migrations.AddField(
            model_name='qboexpenselineitem',
            name='item_id',
            field=models.CharField(help_text='QBO item id', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='billlineitem',
            name='account_id',
            field=models.CharField(help_text='QBO account id', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='chequelineitem',
            name='account_id',
            field=models.CharField(help_text='QBO account id', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='creditcardpurchaselineitem',
            name='account_id',
            field=models.CharField(help_text='QBO account id', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='qboexpenselineitem',
            name='account_id',
            field=models.CharField(help_text='QBO account id', max_length=255, null=True),
        ),
    ]
