# Generated by Django 3.2.14 on 2024-08-28 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickbooks_online', '0014_auto_20230422_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='bill_number',
            field=models.CharField(help_text='Bill Number', max_length=255, null=True),
        ),
    ]
