# Generated by Django 3.2.14 on 2024-09-03 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickbooks_online', '0014_auto_20230422_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='is_retired',
            field=models.BooleanField(default=False, help_text='Is Payment sync retried'),
        ),
    ]
