# Generated by Django 3.2.14 on 2024-11-27 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickbooks_online', '0016_bill_is_retired'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='exchange_rate',
            field=models.FloatField(help_text='Exchange rate', null=True),
        ),
    ]
