# Generated by Django 4.2.20 on 2025-05-13 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickbooks_online', '0018_creditcardpurchase_exchange_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='journal_number',
            field=models.CharField(help_text='Journal number', max_length=255, null=True),
        ),
    ]
