# Generated by Django 4.2.22 on 2025-07-01 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0053_workspaceschedule_is_real_time_export_enabled'),
        ('quickbooks_online', '0019_journalentry_journal_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='QBOWebhookIncoming',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('realm_id', models.CharField(db_index=True, help_text='QBO realm ID', max_length=40)),
                ('entity_type', models.CharField(db_index=True, help_text='Entity type (Account, Item, etc.)', max_length=50)),
                ('destination_id', models.CharField(help_text='QBO destination ID', max_length=50)),
                ('operation_type', models.CharField(db_index=True, help_text='Operation type (Create, Update, Delete)', max_length=20)),
                ('raw_response', models.JSONField(help_text='Complete webhook response')),
                ('additional_workspace_ids', models.JSONField(blank=True, default=list, help_text='Additional workspace IDs that share the same realm_id')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Webhook received timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Webhook updated timestamp')),
                ('workspace', models.ForeignKey(help_text='Reference to workspace', on_delete=django.db.models.deletion.PROTECT, to='workspaces.workspace')),
            ],
            options={
                'db_table': 'qbo_webhook_incoming',
                'indexes': [models.Index(fields=['workspace', 'entity_type', 'created_at'], name='qbo_webhook_workspa_b9506d_idx'), models.Index(fields=['realm_id', 'operation_type'], name='qbo_webhook_realm_i_a1a191_idx')],
            },
        ),
    ]
