# Generated by Django 4.2.22 on 2025-06-27 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0053_workspaceschedule_is_real_time_export_enabled'),
        ('quickbooks_online', '0019_journalentry_journal_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('realm_id', models.CharField(db_index=True, help_text='QBO realm ID', max_length=40)),
                ('entity_type', models.CharField(db_index=True, help_text='Entity type (Account, Item, etc.)', max_length=50)),
                ('entity_id', models.CharField(help_text='QBO entity ID', max_length=50)),
                ('operation', models.CharField(db_index=True, help_text='Operation type (Create, Update, Delete)', max_length=20)),
                ('last_updated', models.DateTimeField(help_text='Entity last updated timestamp')),
                ('raw_payload', models.JSONField(help_text='Complete webhook payload')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Webhook received timestamp')),
                ('workspace', models.ForeignKey(help_text='Reference to workspace', on_delete=django.db.models.deletion.PROTECT, to='workspaces.workspace')),
            ],
            options={
                'db_table': 'qbo_webhook',
                'indexes': [models.Index(fields=['workspace', 'entity_type', 'created_at'], name='qbo_webhook_workspa_42362c_idx'), models.Index(fields=['realm_id', 'operation'], name='qbo_webhook_realm_i_046160_idx')],
            },
        ),
    ]
