# Generated by Django 4.2.22 on 2025-07-14 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0053_workspaceschedule_is_real_time_export_enabled'),
        ('quickbooks_online', '0020_qbowebhookincoming'),
    ]

    operations = [
        migrations.CreateModel(
            name='QBOSyncTimestamp',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('account_synced_at', models.DateTimeField(help_text='Datetime when accounts were synced last', null=True)),
                ('item_synced_at', models.DateTimeField(help_text='Datetime when items were synced last', null=True)),
                ('vendor_synced_at', models.DateTimeField(help_text='Datetime when vendors were synced last', null=True)),
                ('employee_synced_at', models.DateTimeField(help_text='Datetime when employees were synced last', null=True)),
                ('department_synced_at', models.DateTimeField(help_text='Datetime when departments were synced last', null=True)),
                ('tax_code_synced_at', models.DateTimeField(help_text='Datetime when tax codes were synced last', null=True)),
                ('class_synced_at', models.DateTimeField(help_text='Datetime when classes were synced last', null=True)),
                ('customer_synced_at', models.DateTimeField(help_text='Datetime when customers were synced last', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Created at datetime')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Updated at datetime')),
                ('workspace', models.ForeignKey(help_text='Reference to workspace', on_delete=django.db.models.deletion.PROTECT, to='workspaces.workspace')),
            ],
            options={
                'db_table': 'qbo_sync_timestamps',
            },
        ),
    ]
