# Generated by Django 4.2.24 on 2025-09-28 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickbooks_online', '0021_qbosynctimestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qbowebhookincoming',
            name='additional_workspace_ids',
            field=models.JSONField(default=list, help_text='Additional workspace IDs that share the same realm_id'),
        ),
    ]
