# Generated by Django 4.2.26 on 2025-11-21 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0059_alter_featureconfig_fyle_webhook_sync_enabled'),
        ('quickbooks_online', '0022_alter_qbowebhookincoming_additional_workspace_ids'),
    ]

    operations = [
        migrations.CreateModel(
            name='QBOAttributesCount',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('accounts_count', models.IntegerField(default=0, help_text='Number of accounts in QBO')),
                ('items_count', models.IntegerField(default=0, help_text='Number of items in QBO')),
                ('vendors_count', models.IntegerField(default=0, help_text='Number of vendors in QBO')),
                ('employees_count', models.IntegerField(default=0, help_text='Number of employees in QBO')),
                ('departments_count', models.IntegerField(default=0, help_text='Number of departments in QBO')),
                ('classes_count', models.IntegerField(default=0, help_text='Number of classes in QBO')),
                ('customers_count', models.IntegerField(default=0, help_text='Number of customers in QBO')),
                ('tax_codes_count', models.IntegerField(default=0, help_text='Number of tax codes in QBO')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Created at datetime')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Updated at datetime')),
                ('workspace', models.OneToOneField(help_text='Reference to workspace', on_delete=django.db.models.deletion.PROTECT, related_name='qbo_attributes_count', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'qbo_attributes_count',
            },
        ),
    ]
