# Generated by Django 4.2.25 on 2025-12-12 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickbooks_online', '0023_qboattributescount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='accounts_payable_id',
            field=models.CharField(help_text='QBO Accounts Payable account id', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='billpayment',
            name='accounts_payable_id',
            field=models.CharField(help_text='QBO Accounts Payable account id', max_length=255, null=True),
        ),
    ]
