data = {
    'advanced_config':{
        'workspace_general_settings':{
            'sync_fyle_to_qbo_payments':False,
            'sync_qbo_to_fyle_payments':False,
            'auto_create_destination_entity':False,
            'auto_create_merchants_as_vendors':False,
            'je_single_credit_line':False,
            'change_accounting_period':True,
            'memo_structure':[
                'employee_email',
                'category',
                'spent_on',
                'report_number',
                'purpose',
                'expense_link'
            ]
        },
        'general_mappings':{
            'bill_payment_account':{
                'id':'',
                'name':''
            }
        },
        'workspace_schedules':{
            'enabled':True,
            'interval_hours':1,
            'additional_email_options':{
                
            },
            'emails_selected':[
                'fyle@fyle.in'
            ]
        }
    },
    'response':{
        'workspace_general_settings':{
            'sync_fyle_to_qbo_payments':False,
            'sync_qbo_to_fyle_payments':False,
            'auto_create_destination_entity':False,
            'auto_create_merchants_as_vendors':False,
            'je_single_credit_line':False,
            'change_accounting_period':True,
            'memo_structure':[
                'employee_email',
                'category',
                'spent_on',
                'report_number',
                'purpose',
                'expense_link'
            ]
        },
        'general_mappings':{
            'bill_payment_account':{
                'id':'',
                'name':''
            }
        },
        'workspace_schedules':{
            'enabled':True,
            'interval_hours':1,
            'emails_selected':[
                'fyle@fyle.in'
            ],
            'additional_email_options':{
                
            }
        },
        'workspace_id':9
    }
}