# Generated by Django 3.0.2 on 2020-01-13 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='approved_at',
            field=models.DateTimeField(help_text='Expense approved at', null=True),
        ),
    ]
