# Generated by Django 3.0.3 on 2020-06-26 14:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fyle", "0002_auto_20200420_0434"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expensegroup",
            name="fyle_group_id",
            field=models.CharField(
                help_text="fyle expense group id report id, etc", max_length=255
            ),
        ),
    ]
