# Generated by Django 3.0.2 on 2020-01-14 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyle', '0002_expense_approved_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='claim_number',
            field=models.CharField(help_text='Claim Number', max_length=255, null=True, unique=True),
        ),
    ]
