# Generated by Django 3.0.3 on 2020-08-13 12:15

import apps.fyle.models
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0003_auto_20200506_0739'),
        ('fyle', '0003_auto_20200626_1401'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseGroupSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reimbursable_expense_group_fields', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=apps.fyle.models.get_default_expense_group_fields, help_text='list of fields reimbursable expense grouped by', size=None)),
                ('corporate_credit_card_expense_group_fields', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=apps.fyle.models.get_default_expense_group_fields, help_text='list of fields ccc expenses grouped by', size=None)),
                ('expense_states', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=apps.fyle.models.get_default_expense_states, help_text='list of states to fetch expenses', size=None)),
                ('export_date', models.CharField(default='CURRENT_DATE', help_text='Export Date', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Updated at')),
                ('workspace', models.OneToOneField(help_text='To which workspace this expense group setting belongs to', on_delete=django.db.models.deletion.PROTECT, to='workspaces.Workspace')),
            ],
        ),
    ]
