# Generated by Django 3.0.2 on 2020-01-15 11:03

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyle', '0003_expense_claim_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensegroup',
            name='fyle_group_id',
            field=models.CharField(default=None, help_text='fyle expense group id report id, etc', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='expense',
            name='claim_number',
            field=models.CharField(help_text='Claim Number', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='expense_number',
            field=models.CharField(help_text='Expense Number', max_length=255),
        ),
        migrations.AlterField(
            model_name='expensegroup',
            name='description',
            field=django.contrib.postgres.fields.jsonb.JSONField(help_text='Description', max_length=255, null=True),
        ),
    ]
