# Generated by Django 3.0.3 on 2020-04-07 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyle', '0004_auto_20200115_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='fund_source',
            field=models.CharField(default='default', help_text='Expense fund source', max_length=255),
            preserve_default=False,
        ),
    ]
