# Generated by Django 3.0.3 on 2020-08-18 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyle', '0004_expensegroupsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensegroupsettings',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
