# Generated by Django 3.0.3 on 2020-08-19 14:19

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyle', '0004_expensegroupsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='custom_properties',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='rp_created_at',
            field=models.DateTimeField(help_text='Report approved at', null=True),
        ),
        migrations.AlterField(
            model_name='expensegroupsettings',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
