# Generated by Django 3.0.3 on 2020-08-19 10:53

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyle', '0005_auto_20200818_0807'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='custom_properties',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='rp_approved_at',
            field=models.DateTimeField(help_text='Report approved at', null=True),
        ),
    ]
