# Generated by Django 3.0.3 on 2020-08-27 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('fyle', '0006_auto_20200825_0631')]

    operations = [migrations.RemoveField(model_name='expense', name='rp_created_at'), migrations.AddField(model_name='expense', name='verified_at', field=models.DateTimeField(help_text='Report verified at', null=True))]
