# Generated by Django 3.0.3 on 2020-08-19 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fyle', '0006_auto_20200819_1053'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='rp_approved_at',
            new_name='rp_created_at',
        ),
    ]
