# Generated by Django 3.0.3 on 2020-09-29 06:10

import apps.fyle.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyle', '0008_auto_20200901_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensegroupsettings',
            name='expense_states',
            field=models.CharField(default=apps.fyle.models.get_default_expense_states, help_text='list of states to fetch expenses', max_length=100),
        ),
    ]
