# Generated by Django 3.0.3 on 2020-11-19 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fyle", "0011_expensegroup_exported_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="billable",
            field=models.BooleanField(help_text="Expense Billable or not", null=True),
        ),
    ]
