# Generated by Django 3.0.3 on 2020-12-21 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fyle", "0012_expense_billable"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="expense",
            table="expenses",
        ),
        migrations.AlterModelTable(
            name="expensegroup",
            table="expense_groups",
        ),
        migrations.AlterModelTable(
            name="expensegroupsettings",
            table="expense_group_settings",
        ),
    ]
