# Generated by Django 3.0.3 on 2021-08-03 07:43

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [('fyle', '0015_expense_org_id')]

    operations = [migrations.AddField(model_name='expensegroup', name='response_logs', field=django.contrib.postgres.fields.jsonb.JSONField(help_text='Reponse log of the export', null=True))]
