# Generated by Django 3.0.3 on 2021-08-20 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fyle", "0016_expensegroup_response_logs"),
    ]

    operations = [
        migrations.AddField(
            model_name="expensegroupsettings",
            name="import_card_credits",
            field=models.BooleanField(default=False, help_text="Import Card Credits"),
        ),
    ]
