# Generated by Django 3.1.13 on 2022-01-08 16:41

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyle', '0021_auto_20211210_0726'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='file_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), help_text='File IDs', null=True, size=None),
        ),
    ]
