# Generated by Django 3.1.13 on 2022-01-23 11:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fyle", "0022_expense_file_ids"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="corporate_card_id",
            field=models.CharField(
                blank=True, help_text="Corporate Card ID", max_length=255, null=True
            ),
        ),
    ]
