# Generated by Django 3.1.14 on 2022-03-22 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0025_auto_20220322_0955'),
        ('fyle', '0023_expense_corporate_card_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensegroupsettings',
            name='workspace',
            field=models.OneToOneField(help_text='To which workspace this expense group setting belongs to', on_delete=django.db.models.deletion.PROTECT, related_name='expense_group_settings', to='workspaces.workspace'),
        ),
    ]
