# Generated by Django 3.1.14 on 2022-03-30 11:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fyle", "0024_auto_20220323_0914"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="employee_name",
            field=models.CharField(
                help_text="Name of the Fyle employee", max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="expensegroup",
            name="employee_name",
            field=models.CharField(
                help_text="Expense Group Employee Name", max_length=100, null=True
            ),
        ),
    ]
