# Generated by Django 3.1.14 on 2023-01-12 10:50

from django.db import migrations, models

import apps.fyle.models


class Migration(migrations.Migration):

    dependencies = [
        ("fyle", "0027_expensegroupsettings_ccc_expense_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expensegroupsettings",
            name="expense_state",
            field=models.CharField(
                default=apps.fyle.models.get_default_expense_state,
                help_text="state at which the expenses are fetched ( PAYMENT_PENDING / PAYMENT_PROCESSING, PAID)",
                max_length=100,
                null=True,
            ),
        ),
    ]
