# Generated by Django 3.1.14 on 2023-09-01 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyle', '0031_auto_20230801_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='accounting_export_summary',
            field=models.JSONField(default=dict),
        ),
    ]
