# Generated by Django 3.1.14 on 2023-09-07 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyle', '0033_expense_workspace'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='previous_export_state',
            field=models.CharField(help_text='Previous export state', max_length=255, null=True),
        ),
    ]
