# Generated by Django 3.2.14 on 2024-05-14 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyle', '0034_expense_previous_export_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensefilter',
            name='custom_field_type',
            field=models.CharField(choices=[('SELECT', 'SELECT'), ('NUMBER', 'NUMBER'), ('TEXT', 'TEXT'), ('BOOLEAN', 'BOOLEAN')], help_text='Custom field type', max_length=255, null=True),
        ),
    ]
