# Generated by Django 3.2.14 on 2024-06-24 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyle', '0036_expense_paid_on_fyle'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='bank_transaction_id',
            field=models.CharField(blank=True, help_text='Bank Transaction ID', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='expensegroupsettings',
            name='split_expense_grouping',
            field=models.CharField(choices=[('SINGLE_LINE_ITEM', 'SINGLE_LINE_ITEM'), ('MULTIPLE_LINE_ITEM', 'MULTIPLE_LINE_ITEM')], default='SINGLE_LINE_ITEM', help_text='specify line items for split expenses grouping', max_length=100, null=True),
        ),
    ]
