# Generated by Django 3.2.14 on 2024-08-03 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyle', '0037_auto_20240625_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensegroup',
            name='export_url',
            field=models.CharField(help_text='QBO URL for the exported expenses', max_length=255, null=True),
        ),
    ]
