# Generated by Django 4.2.20 on 2025-04-09 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyle', '0042_expense_imported_from'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['accounting_export_summary'], name='expenses_account_ddcaed_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['fund_source'], name='expenses_fund_so_eb83bb_idx'),
        ),
    ]
