# Generated by Django
from django.db import migrations

class Migration(migrations.Migration):
    dependencies = [('internal', '0002_auto_generated_sql')]

    operations = [
        migrations.RunSQL(
            sql="""
                INSERT INTO django_q_schedule (func, args, schedule_type, minutes, next_run)
                    SELECT 'apps.internal.actions.re_export_stuck_exports', NULL, 1, 180, NOW()
                    WHERE NOT EXISTS (
                        SELECT 1
                        FROM django_q_schedule
                        WHERE func = 'apps.internal.actions.re_export_stuck_exports'
                        AND args IS NULL
                    );
            """
        ),
    ]
    
