# Generated by Django
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [('internal', '0002_auto_generated_sql')]

    operations = [
        migrations.RunSQL(
            sql="""
                INSERT INTO django_q_schedule (func, args, schedule_type, minutes, next_run, cluster)
                    SELECT 'apps.internal.actions.re_export_stuck_exports', NULL, 1, 180, NOW() + INTERVAL '1 minute', 'import'
                    WHERE NOT EXISTS (
                        SELECT 1
                        FROM django_q_schedule
                        WHERE func = 'apps.internal.tasks.re_export_stuck_exports'
                        AND args IS NULL
                    );
            """,
            reverse_sql="""
                DELETE FROM django_q_schedule
                WHERE func = 'apps.internal.tasks.re_export_stuck_exports'
                AND args IS NULL;
            """
        )
    ]
