# Generated by Django
from django.db import migrations

sql_files = [
    'fyle-integrations-db-migrations/intacct/views/product_export_settings_view.sql',
    'fyle-integrations-db-migrations/netsuite/views/product_export_settings_view.sql',
    'fyle-integrations-db-migrations/qbo/views/product_export_settings_view.sql',
    'fyle-integrations-db-migrations/xero/views/product_export_settings_view.sql'
]

class Migration(migrations.Migration):
    dependencies = [('internal', '0003_auto_generated_sql')]
    operations = safe_run_sql(sql_files)
