# Generated by Django
from django.db import migrations
from apps.internal.helpers import safe_run_sql

sql_files = [
    'fyle-integrations-db-migrations/qbo/functions/delete_workspace.sql'
]


class Migration(migrations.Migration):
    dependencies = [('internal', '0008_auto_generated_sql'), ('quickbooks_online', '0020_qbowebhookincoming')]
    operations = safe_run_sql(sql_files)
