# Generated by Django
from django.db import migrations
from apps.internal.helpers import safe_run_sql

sql_files = [
    'fyle-integrations-db-migrations/qbo/helpers/insert_qbo_sync_timestamp_row.sql'
]


class Migration(migrations.Migration):
    dependencies = [('internal', '0009_auto_generated_sql'), ('quickbooks_online', '0021_qbosynctimestamp')]
    operations = safe_run_sql(sql_files)
