# Generated by Django
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [('internal', '0011_auto_generated_sql')]

    operations = [
        migrations.RunSQL(
            sql="""
                update django_q_schedule set cluster = null where cluster = 'import;
            """,
            reverse_sql="""
            """
        )
    ]
