# Generated by Django
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [('quickbooks_online', '0023_qboattributescount'), ('internal', '0016_auto_generated_sql')]

    operations = [
        migrations.RunSQL(
            sql="""
                INSERT INTO qbo_attributes_count (workspace_id, created_at, updated_at)
                SELECT id, now(), now()
                FROM workspaces
                WHERE NOT EXISTS (
                    SELECT 1
                    FROM qbo_attributes_count
                    WHERE workspace_id = workspaces.id
                );
            """,
            reverse_sql="""
                DELETE FROM qbo_attributes_count
                WHERE EXISTS (
                    SELECT 1
                    FROM qbo_attributes_count
                    WHERE workspace_id = qbo_attributes_count.workspace_id
                );
            """
        )
    ]
