# Generated by Django 3.1.14 on 2022-10-06 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_q', '0013_task_attempt_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrmQExtension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('orm_q', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extension', to='django_q.ormq')),
            ],
        ),
    ]
