# Generated by Django 3.2.14 on 2024-09-08 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(help_text='Role of the messenger', max_length=255)),
                ('content', models.TextField(help_text='Content of the message')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Created at datetime')),
            ],
        ),
    ]
