# Generated by Django 3.2.14 on 2024-09-09 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration_helper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='conversation_id',
            field=models.CharField(help_text='Unique id of the conversation', max_length=255),
            preserve_default=False,
        ),
    ]
