# Generated by Django 3.2.14 on 2024-09-09 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integration_helper', '0002_conversation_conversation_id'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='conversation',
            table='conversations',
        ),
    ]
