# Generated by Django 3.0.3 on 2020-03-10 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("workspaces", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GeneralMapping",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "bank_account_name",
                    models.CharField(
                        help_text="Name of the bank account", max_length=255
                    ),
                ),
                (
                    "bank_account_id",
                    models.CharField(help_text="QBO bank account id", max_length=40),
                ),
                (
                    "default_ccc_account_name",
                    models.CharField(
                        help_text="Name of the default ccc account", max_length=255
                    ),
                ),
                (
                    "default_ccc_account_id",
                    models.CharField(
                        help_text="QBO default ccc account id", max_length=40
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Created at datetime"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Updated at datetime"
                    ),
                ),
                (
                    "workspace",
                    models.OneToOneField(
                        help_text="Reference to Workspace model",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="workspaces.Workspace",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProjectMapping",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("project", models.CharField(help_text="Fyle project", max_length=255)),
                (
                    "customer_display_name",
                    models.CharField(help_text="QBO customer name", max_length=255),
                ),
                (
                    "customer_id",
                    models.CharField(help_text="QBO customer id", max_length=255),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Created at datetime"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Updated at datetime"
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        help_text="Reference to Workspace model",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="workspaces.Workspace",
                    ),
                ),
            ],
            options={
                "unique_together": {("project", "workspace")},
            },
        ),
        migrations.CreateModel(
            name="CostCenterMapping",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "cost_center",
                    models.CharField(help_text="Fyle cost center", max_length=255),
                ),
                (
                    "class_name",
                    models.CharField(help_text="QBO class name", max_length=255),
                ),
                (
                    "class_id",
                    models.CharField(help_text="QBO class id", max_length=255),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Created at datetime"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Updated at datetime"
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        help_text="Reference to Workspace model",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="workspaces.Workspace",
                    ),
                ),
            ],
            options={
                "unique_together": {("cost_center", "workspace")},
            },
        ),
    ]
