# Generated by Django 3.0.2 on 2020-01-10 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mappings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeemapping',
            name='ccc_account',
            field=models.CharField(default='', help_text='QBO CCC account name', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employeemapping',
            name='ccc_account_id',
            field=models.CharField(default='', help_text='QBO CCC account id', max_length=255),
            preserve_default=False,
        ),
    ]
