# Generated by Django 3.0.2 on 2020-01-11 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mappings', '0002_auto_20200110_0923'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeemapping',
            name='ccc_account',
        ),
        migrations.RemoveField(
            model_name='employeemapping',
            name='ccc_account_id',
        ),
    ]
