# Generated by Django 3.0.3 on 2020-12-21 07:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mappings", "0003_auto_20200930_0738"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="costcentermapping",
            table="cost_center_mappings",
        ),
        migrations.AlterModelTable(
            name="generalmapping",
            table="general_mappings",
        ),
        migrations.AlterModelTable(
            name="projectmapping",
            table="project_mappings",
        ),
    ]
