# Generated by Django 3.0.2 on 2020-01-11 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0001_initial'),
        ('mappings', '0003_auto_20200111_2216'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='employeemapping',
            unique_together={('employee_email', 'workspace')},
        ),
    ]
