# Generated by Django 3.0.2 on 2020-01-13 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0001_initial'),
        ('mappings', '0004_auto_20200111_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalmapping',
            name='workspace',
            field=models.OneToOneField(help_text='Reference to Workspace model', on_delete=django.db.models.deletion.PROTECT, to='workspaces.Workspace'),
        ),
        migrations.AlterUniqueTogether(
            name='categorymapping',
            unique_together={('category', 'sub_category', 'workspace')},
        ),
        migrations.AlterUniqueTogether(
            name='costcentermapping',
            unique_together={('cost_center', 'workspace')},
        ),
        migrations.AlterUniqueTogether(
            name='projectmapping',
            unique_together={('project', 'workspace')},
        ),
        migrations.RemoveField(
            model_name='categorymapping',
            name='updated_at',
        ),
    ]
