# Generated by Django 3.0.3 on 2021-05-04 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('mappings', '0005_auto_20210120_1851')]

    operations = [
        migrations.AddField(
            model_name='generalmapping',
            name='qbo_expense_account_id',
            field=models.CharField(
                help_text='QBO Expense Account id', max_length=40, null=True
            ),
        ),
        migrations.AddField(
            model_name='generalmapping',
            name='qbo_expense_account_name',
            field=models.CharField(
                help_text='Name of the QBO Expense account', max_length=255, null=True
            ),
        ),
    ]
