# Generated by Django 3.0.3 on 2021-03-04 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mappings', '0005_auto_20210120_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalmapping',
            name='map_merchant_to_vendor',
            field=models.BooleanField(default=False, help_text='Map Merchant to Vendor for CCC Expenses'),
        ),
    ]
