# Generated by Django 3.0.2 on 2020-01-13 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mappings', '0005_auto_20200113_0700'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorymapping',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Updated at datetime'),
        ),
    ]
