# Generated by Django 3.0.3 on 2021-07-22 14:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mappings", "0006_auto_20210504_1913"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="costcentermapping",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="costcentermapping",
            name="workspace",
        ),
        migrations.AlterUniqueTogether(
            name="projectmapping",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="projectmapping",
            name="workspace",
        ),
        migrations.DeleteModel(
            name="CostCenterMapping",
        ),
        migrations.DeleteModel(
            name="ProjectMapping",
        ),
    ]
