# Generated by Django 3.0.3 on 2020-02-15 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mappings', '0006_categorymapping_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectmapping',
            name='department_id',
        ),
        migrations.RemoveField(
            model_name='projectmapping',
            name='department_name',
        ),
        migrations.AddField(
            model_name='projectmapping',
            name='customer_display_name',
            field=models.CharField(default='', help_text='QBO customer name', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectmapping',
            name='customer_id',
            field=models.CharField(default='', help_text='QBO customer id', max_length=255),
            preserve_default=False,
        ),
    ]
