# Generated by Django 3.0.3 on 2020-04-07 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mappings', '0007_auto_20200215_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeemapping',
            name='ccc_account_id',
            field=models.CharField(default=1234, help_text='QBO ccc account id', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employeemapping',
            name='ccc_account_name',
            field=models.CharField(default='default', help_text='Name of the ccc account', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employeemapping',
            name='employee_display_name',
            field=models.CharField(default=1234, help_text='QBO employee display name', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employeemapping',
            name='employee_id',
            field=models.CharField(default=1234, help_text='QBO employee id', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='generalmapping',
            name='accounts_payable_id',
            field=models.CharField(default=1234, help_text='QBO accounts payable bank account id', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='generalmapping',
            name='accounts_payable_name',
            field=models.CharField(default='default', help_text='Name of the accounts payable bank account', max_length=255),
            preserve_default=False,
        ),
    ]
