# Generated by Django 3.1.14 on 2022-03-23 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("workspaces", "0026_auto_20220323_0914"),
        ("mappings", "0009_auto_20220215_0843"),
    ]

    operations = [
        migrations.AlterField(
            model_name="generalmapping",
            name="workspace",
            field=models.OneToOneField(
                help_text="Reference to Workspace model",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="general_mappings",
                to="workspaces.workspace",
            ),
        ),
    ]
