# Generated by Django 3.0.3 on 2020-04-20 04:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('workspaces', '0001_initial')]

    operations = [
        migrations.CreateModel(
            name='WorkspaceGeneralSettings',
            fields=[
                (
                    'id',
                    models.AutoField(
                        help_text='Unique Id to identify a workspace',
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    'reimbursable_expenses_object',
                    models.CharField(
                        help_text='Reimbursable Expenses type', max_length=50
                    ),
                ),
                (
                    'corporate_credit_card_expenses_object',
                    models.CharField(
                        help_text='Non Reimbursable Expenses type',
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    'employee_field_mapping',
                    models.CharField(
                        help_text='Mapping Settings ( VENDOR / EMPLOYEE )',
                        max_length=50,
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(auto_now_add=True, help_text='Created at'),
                ),
                (
                    'updated_at',
                    models.DateTimeField(auto_now=True, help_text='Updated at'),
                ),
                (
                    'workspace',
                    models.OneToOneField(
                        help_text='Reference to Workspace model',
                        on_delete=django.db.models.deletion.PROTECT,
                        to='workspaces.Workspace',
                    ),
                ),
            ],
        )
    ]
