# Generated by Django 3.0.3 on 2020-02-15 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0002_workspace_last_synced_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='fyle_org_id',
            field=models.CharField(default='orPJvXuoLqvJ', help_text='org id', max_length=255),
            preserve_default=False,
        ),
    ]
