# Generated by Django 3.0.3 on 2020-02-15 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0003_workspace_fyle_org_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='qbo_realm_id',
            field=models.CharField(default='', help_text='qbo realm id', max_length=255),
            preserve_default=False,
        ),
    ]
