# Generated by Django 3.0.3 on 2020-02-18 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_q', '0009_auto_20171009_0915'),
        ('workspaces', '0004_workspace_qbo_realm_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkspaceSettings',
            fields=[
                ('id', models.AutoField(help_text='Unique Id to identify a workspace settings', primary_key=True, serialize=False)),
                ('schedule_enabled', models.BooleanField(default=False)),
                ('schedule', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='django_q.Schedule')),
            ],
        ),
    ]
