# Generated by Django 3.0.3 on 2020-11-25 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workspaces", "0004_workspacegeneralsettings_import_projects"),
    ]

    operations = [
        migrations.AddField(
            model_name="workspacegeneralsettings",
            name="import_categories",
            field=models.BooleanField(
                default=False, help_text="Auto import Categories to Fyle"
            ),
        ),
    ]
