# Generated by Django 3.0.3 on 2020-02-19 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0006_auto_20200218_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspacesettings',
            name='workspace',
            field=models.OneToOneField(default=None, help_text='Reference to Workspace model', on_delete=django.db.models.deletion.PROTECT, to='workspaces.Workspace'),
            preserve_default=False,
        ),
    ]
