# Generated by Django 3.0.3 on 2020-02-21 13:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workspaces', '0007_workspacesettings_workspace'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workspace',
            name='user',
        ),
        migrations.AddField(
            model_name='workspace',
            name='user',
            field=models.ManyToManyField(help_text='Reference to users table', to=settings.AUTH_USER_MODEL),
        ),
    ]
