# Generated by Django 3.0.3 on 2021-02-09 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0007_auto_20210209_0656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspaceschedule',
            name='workspace',
            field=models.OneToOneField(help_text='Reference to Workspace model', on_delete=django.db.models.deletion.PROTECT, to='workspaces.Workspace'),
        ),
    ]
