# Generated by Django 3.0.3 on 2020-04-07 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0009_auto_20200308_0708'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkspaceGeneralSettings',
            fields=[
                ('id', models.AutoField(help_text='Unique Id to identify a workspace', primary_key=True, serialize=False)),
                ('reimbursable_expenses_object', models.CharField(help_text='Reimbursable Expenses type', max_length=50)),
                ('corporate_credit_card_expenses_object', models.CharField(help_text='Non Reimbursable Expenses type', max_length=50)),
                ('employee_field_mapping', models.CharField(help_text='Mapping Settings ( VENDORS / EMPLOYEES )', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Updated at')),
                ('workspace', models.OneToOneField(help_text='Reference to Workspace model', on_delete=django.db.models.deletion.PROTECT, to='workspaces.Workspace')),
            ],
        ),
    ]
