# Generated by Django 3.0.3 on 2021-04-28 08:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workspaces", "0012_workspacegeneralsettings_map_merchant_to_vendor"),
    ]

    operations = [
        migrations.AddField(
            model_name="workspace",
            name="destination_synced_at",
            field=models.DateTimeField(
                help_text="Datetime when destination dimensions were pulled", null=True
            ),
        ),
        migrations.AddField(
            model_name="workspace",
            name="source_synced_at",
            field=models.DateTimeField(
                help_text="Datetime when source dimensions were pulled", null=True
            ),
        ),
    ]
