# Generated by Django 3.0.3 on 2021-07-14 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('workspaces', '0013_auto_20210428_0855')]

    operations = [
        migrations.AddField(
            model_name='workspacegeneralsettings',
            name='je_single_credit_line',
            field=models.BooleanField(
                default=False, help_text='Single Credit Line for Journal Entries'
            ),
        )
    ]
