# Generated by Django 3.0.3 on 2021-08-12 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0014_workspacegeneralsettings_je_single_credit_line'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspacegeneralsettings',
            name='import_taxcodes',
            field=models.BooleanField(default=False, help_text='Auto import tax codes to Fyle'),
        ),
    ]
