# Generated by Django 3.0.3 on 2021-09-15 13:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workspaces", "0014_workspacegeneralsettings_je_single_credit_line"),
    ]

    operations = [
        migrations.AddField(
            model_name="workspacegeneralsettings",
            name="change_accounting_period",
            field=models.BooleanField(
                default=False,
                help_text="Export Expense when accounting period is closed",
            ),
        ),
    ]
