# Generated by Django 3.0.3 on 2021-09-06 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0015_workspacegeneralsettings_import_taxcodes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspacegeneralsettings',
            name='import_tax_codes',
            field=models.BooleanField(default=False, help_text='Auto import tax codes to Fyle', null=True),
        ),
    ]
