# Generated by Django 3.0.3 on 2021-09-13 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0016_auto_20210906_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='qbocredential',
            name='company_name',
            field=models.CharField(help_text='QBO Company Name', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='qbocredential',
            name='country',
            field=models.CharField(help_text='QBO Country Name', max_length=255, null=True),
        ),
    ]
