# Generated by Django 3.0.3 on 2021-09-24 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0016_auto_20210917_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='cluster_domain',
            field=models.CharField(help_text='fyle cluster domain', max_length=255, null=True),
        ),
    ]
