# Generated by Django 3.1.13 on 2021-12-10 12:29

import apps.workspaces.models
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0018_workspacegeneralsettings_charts_of_accounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspacegeneralsettings',
            name='customized_memo',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=apps.workspaces.models.get_default_memo_fields, help_text='list of system fields for creating custom memo', size=None),
        ),
    ]
