# Generated by Django 3.1.13 on 2021-12-22 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0018_workspacegeneralsettings_charts_of_accounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspaceschedule',
            name='total_errors',
            field=models.IntegerField(null=True),
        ),
    ]
