# Generated by Django 3.0.3 on 2021-12-01 06:39

import apps.workspaces.models
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0018_workspacegeneralsettings_charts_of_accounts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspacegeneralsettings',
            name='charts_of_accounts',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=apps.workspaces.models.get_default_chart_of_accounts, help_text='list of chart of account types to be imported into Fyle', size=None),
        ),
    ]
