# Generated by Django 3.1.13 on 2022-01-13 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workspaces", "0019_workspacegeneralsettings_memo_structure"),
    ]

    operations = [
        migrations.AddField(
            model_name="fylecredential",
            name="cluster_domain",
            field=models.CharField(
                help_text="Cluster Domain", max_length=255, null=True
            ),
        ),
    ]
