# Generated by Django 3.1.13 on 2022-01-23 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('workspaces', '0020_fylecredential_cluster_domain')]

    operations = [migrations.AddField(model_name='workspacegeneralsettings', name='map_fyle_cards_qbo_account', field=models.BooleanField(default=True, help_text='Map Fyle Cards to QBO Accounts'))]
