# Generated by Django 3.1.14 on 2022-02-01 12:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workspaces", "0021_workspacegeneralsettings_map_fyle_cards_qbo_account"),
    ]

    operations = [
        migrations.AddField(
            model_name="workspacegeneralsettings",
            name="skip_cards_mapping",
            field=models.BooleanField(default=False, help_text="Skip cards mapping"),
        ),
    ]
