# Generated by Django 3.1.13 on 2022-01-25 23:57

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0021_workspaceschedule_total_errors'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspaceschedule',
            name='emails',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), help_text='Admin Email', null=True, size=None),
        ),
    ]
