# Generated by Django 3.1.14 on 2022-03-14 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('workspaces', '0022_workspacegeneralsettings_skip_cards_mapping')]

    operations = [migrations.AlterField(model_name='qbocredential', name='refresh_token', field=models.TextField(help_text='Stores QBO refresh token', null=True))]
