# Generated by Django 3.1.14 on 2022-02-26 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0022_workspacegeneralsettings_skip_cards_mapping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspacegeneralsettings',
            name='workspace',
            field=models.OneToOneField(help_text='Reference to Workspace model', on_delete=django.db.models.deletion.PROTECT, related_name='workspace_general_settings', to='workspaces.workspace'),
        ),
    ]
