# Generated by Django 3.1.14 on 2022-02-28 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0023_auto_20220226_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspacegeneralsettings',
            name='reimbursable_expenses_object',
            field=models.CharField(help_text='Reimbursable Expenses type', max_length=50, null=True),
        ),
    ]
