# Generated by Django 3.1.14 on 2022-02-28 12:26

import apps.workspaces.apis.import_settings.models
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0024_auto_20220228_1118'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportSetting',
            fields=[
                ('id', models.AutoField(help_text='Unique Id to identify a workspace', primary_key=True, serialize=False)),
                ('import_accounts', models.BooleanField(default=False, help_text='Auto import accounts to Fyle')),
                ('charts_of_accounts', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=apps.workspaces.apis.import_settings.models.get_default_chart_of_accounts, help_text='list of chart of account types to be imported into Fyle', size=None)),
                ('account_sync_version', models.CharField(default='v1', help_text='Category sync version', max_length=50)),
                ('import_customers', models.BooleanField(default=False, help_text='Auto import customers to Fyle')),
                ('customers_mapped_to', models.CharField(help_text='Customer mapping field', max_length=50, null=True)),
                ('import_classes', models.BooleanField(default=False, help_text='Auto import classes to Fyle')),
                ('classes_mapped_to', models.CharField(help_text='Class mapping field', max_length=50, null=True)),
                ('import_departments', models.BooleanField(default=False, help_text='Auto import departments to Fyle')),
                ('departments_mapped_to', models.CharField(help_text='Department mapping field', max_length=50, null=True)),
                ('import_tax_codes', models.BooleanField(default=False, help_text='Auto import tax codes to Fyle', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Updated at')),
                ('workspace', models.OneToOneField(help_text='Reference to Workspace model', on_delete=django.db.models.deletion.PROTECT, related_name='import_settings', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'import_settings',
            },
        ),
    ]
