# Generated by Django 3.1.14 on 2022-03-22 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0024_qbocredential_is_expired'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='fyle_currency',
            field=models.CharField(help_text='Fyle Currency', max_length=5, null=True),
        ),
    ]
