# Generated by Django 3.1.14 on 2022-03-29 06:47

import apps.workspaces.models
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0026_auto_20220323_0914'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspacegeneralsettings',
            name='onboarding_state',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=apps.workspaces.models.get_default_onboarding_state, help_text='Onboarding status of the workspace', null=True, size=None),
        ),
    ]
