# Generated by Django 3.1.14 on 2022-03-29 08:51

from django.db import migrations, models

import apps.workspaces.models


class Migration(migrations.Migration):

    dependencies = [
        ("workspaces", "0026_auto_20220323_0914"),
    ]

    operations = [
        migrations.AddField(
            model_name="workspace",
            name="onboarding_state",
            field=models.CharField(
                choices=[
                    ("CONNECTION", "CONNECTION"),
                    ("MAP_EMPLOYEES", "MAP_EMPLOYEES"),
                    ("EXPORT_SETTINGS", "EXPORT_SETTINGS"),
                    ("IMPORT_SETTINGS", "IMPORT_SETTINGS"),
                    ("ADVANCED_CONFIGURATION", "ADVANCED_CONFIGURATION"),
                    ("COMPLETE", "COMPLETE"),
                ],
                default=apps.workspaces.models.get_default_onboarding_state,
                help_text="Onboarding status of the workspace",
                max_length=50,
                null=True,
            ),
        ),
    ]
