# Generated by Django 3.1.14 on 2022-04-20 13:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0029_pastexportdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspaceschedule',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Created at datetime'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workspaceschedule',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Updated at datetime'),
        ),
    ]
