# Generated by Django 3.1.14 on 2022-05-17 09:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workspaces", "0030_workspace_app_version"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workspace",
            name="app_version",
            field=models.CharField(
                choices=[("v1", "v1"), ("v2", "v2")],
                default="v1",
                help_text="App version",
                max_length=2,
            ),
        ),
    ]
