# Generated by Django 3.1.14 on 2022-06-02 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('workspaces', '0031_auto_20220517_0931')]

    operations = [
        migrations.AlterField(
            model_name='qbocredential',
            name='realm_id',
            field=models.CharField(
                help_text='QBO realm / company Id', max_length=40, null=True
            ),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='qbo_realm_id',
            field=models.CharField(help_text='qbo realm id', max_length=255, null=True),
        ),
    ]
