# Generated by Django 3.1.14 on 2022-07-14 09:11

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workspaces", "0032_auto_20220602_1157"),
    ]

    operations = [
        migrations.AddField(
            model_name="workspaceschedule",
            name="additional_email_options",
            field=models.JSONField(
                default=list,
                help_text="Email and Name of person to send email",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="workspaceschedule",
            name="emails_selected",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=255),
                help_text="Emails that has to be send mail",
                null=True,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="workspaceschedule",
            name="error_count",
            field=models.IntegerField(
                help_text="Number of errors in export", null=True
            ),
        ),
        migrations.AlterField(
            model_name="workspaceschedule",
            name="workspace",
            field=models.OneToOneField(
                help_text="Reference to Workspace model",
                on_delete=django.db.models.deletion.PROTECT,
                to="workspaces.workspace",
            ),
        ),
    ]
