# Generated by Django 3.1.14 on 2022-07-15 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workspaces", "0033_auto_20220714_0911"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workspaceschedule",
            name="workspace",
            field=models.OneToOneField(
                help_text="Reference to Workspace model",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="workspace_schedules",
                to="workspaces.workspace",
            ),
        ),
    ]
