# Generated by Django 3.1.14 on 2023-04-19 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workspaces", "0039_qbocredential_currency"),
    ]

    operations = [
        migrations.AddField(
            model_name="workspacegeneralsettings",
            name="is_multi_currency_allowed",
            field=models.BooleanField(
                default=False, help_text="Multi Currency Allowed"
            ),
        ),
    ]
