# Generated by Django 3.1.14 on 2023-08-02 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0041_workspacegeneralsettings_import_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspacegeneralsettings',
            name='name_in_journal_entry',
            field=models.CharField(
                choices=[('MERCHANT', 'MERCHANT'),
                ('EMPLOYEE', 'EMPLOYEE')],
                default='EMPLOYEE',
                help_text='Name in journal entry for ccc expense only',
                max_length=100
            ),
        ),
    ]
