# Generated by Django 3.1.14 on 2024-01-16 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0042_workspacegeneralsettings_name_in_journal_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='lastexportdetail',
            name='next_export_at',
            field=models.DateTimeField(help_text='Next export datetime', null=True),
        ),
    ]
