# Generated by Django 3.2.14 on 2024-06-22 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0043_lastexportdetail_next_export_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspacegeneralsettings',
            name='is_tax_override_enabled',
            field=models.BooleanField(default=False, help_text='Tax Override Enabled'),
        ),
    ]
