# Generated by Django 3.2.14 on 2024-07-16 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0044_workspacegeneralsettings_is_tax_override_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspacegeneralsettings',
            name='is_tax_override_enabled',
            field=models.BooleanField(default=True, help_text='Tax Override Enabled'),
        ),
    ]
