# Generated by Django 3.2.14 on 2024-08-01 10:27

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0045_alter_workspacegeneralsettings_is_tax_override_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspacegeneralsettings',
            name='import_code_fields',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('ACCOUNT', 'ACCOUNT')], max_length=255), blank=True, default=list, help_text='Code Preference List', size=None),
        ),
    ]
