# Generated by Django 4.2.20 on 2025-03-29 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0050_auto_20241226_1155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workspacegeneralsettings',
            name='is_simplify_report_closure_enabled',
        ),
    ]
