# Generated by Django 4.2.20 on 2025-03-29 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0051_remove_workspacegeneralsettings_is_simplify_report_closure_enabled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workspacegeneralsettings',
            name='is_tax_override_enabled',
        ),
    ]
