# Generated by Django 4.2.20 on 2025-03-29 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0052_remove_workspacegeneralsettings_is_tax_override_enabled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workspacegeneralsettings',
            name='skip_cards_mapping',
        ),
    ]
