# Generated by Django 4.2.22 on 2025-07-22 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0053_workspaceschedule_is_real_time_export_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspacegeneralsettings',
            name='is_sync_after_timestamp_enabled',
            field=models.BooleanField(default=False, help_text='Sync after timestamp enabled'),
        ),
    ]
