# Generated by Django 4.2.22 on 2025-08-04 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0054_workspacegeneralsettings_is_sync_after_timestamp_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='lastexportdetail',
            name='unmapped_card_count',
            field=models.IntegerField(default=0, help_text='count of unmapped card'),
        ),
    ]
