# Generated by Django 4.2.22 on 2025-08-13 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0055_lastexportdetail_unmapped_card_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workspacegeneralsettings',
            name='is_sync_after_timestamp_enabled',
        ),
    ]
