# Generated by Django 4.2.24 on 2025-09-11 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0055_lastexportdetail_unmapped_card_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspacegeneralsettings',
            name='is_sync_after_timestamp_enabled',
            field=models.BooleanField(default=True, help_text='Sync after timestamp enabled'),
        ),
    ]
