# Generated by Django 4.2.24 on 2025-09-22 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0056_alter_workspacegeneralsettings_is_sync_after_timestamp_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureConfig',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('export_via_rabbitmq', models.BooleanField(default=True, help_text='Enable export via rabbitmq')),
                ('import_via_rabbitmq', models.BooleanField(default=True, help_text='Enable import via rabbitmq')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Created at datetime')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Updated at datetime')),
                ('workspace', models.OneToOneField(help_text='Reference to Workspace model', on_delete=django.db.models.deletion.PROTECT, to='workspaces.workspace')),
            ],
            options={
                'db_table': 'feature_configs',
            },
        ),
    ]
