# Generated by Django 4.2.24 on 2025-09-30 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0057_featureconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='featureconfig',
            name='fyle_webhook_sync_enabled',
            field=models.BooleanField(default=False, help_text='Enable fyle attribute webhook sync'),
        ),
    ]
