name: Lint and Format Check
on:
  push:
    branches: [ master ]
  pull_request:
    branches:
      - '**'

jobs:
  lint-and-format-check:
    name: Lint and Format Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Run check
        run: |
          python3 -m pip install pre-commit
          pre-commit run --all-files